[build]
  publish = "netlify/"
[functions]
  external_node_modules = ["express","socket.io","web3"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/:splat"
